/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.glehenaff.gestform.view;

import java.util.List;
import org.glehenaff.gestform.model.ECF;
import org.glehenaff.gestform.model.Stagiaire;

/**
 *
 * @author gwenole
 */
public class AddResultatToECF extends javax.swing.JDialog {

    // Model du tableau de résultat
    private final ResTableModel tblResModel;

    /**
     * Creates new form AddResultatToECF
     *
     * @param parent fenètre parente
     * @param modal active l'option en modal
     * @param stagiaires liste de stagaire de la formation
     * @param ecf des résultats à modifier
     */
    public AddResultatToECF(java.awt.Frame parent, boolean modal, List<Stagiaire> stagiaires, ECF ecf) {
        super(parent, modal);
        tblResModel = new ResTableModel(stagiaires, ecf);
        initComponents();
        super.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBtn = new javax.swing.JPanel();
        btnFermer = new javax.swing.JButton();
        panTbl = new javax.swing.JPanel();
        sclRes = new javax.swing.JScrollPane();
        tblRes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });
        panBtn.add(btnFermer);

        getContentPane().add(panBtn, java.awt.BorderLayout.PAGE_END);

        panTbl.setBorder(javax.swing.BorderFactory.createTitledBorder("Résultats"));
        panTbl.setLayout(new javax.swing.BoxLayout(panTbl, javax.swing.BoxLayout.LINE_AXIS));

        tblRes.setModel(tblResModel);
        sclRes.setViewportView(tblRes);

        panTbl.add(sclRes);

        getContentPane().add(panTbl, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    public ResTableModel getTblResModel() {
        return tblResModel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFermer;
    private javax.swing.JPanel panBtn;
    private javax.swing.JPanel panTbl;
    private javax.swing.JScrollPane sclRes;
    private javax.swing.JTable tblRes;
    // End of variables declaration//GEN-END:variables
}
