/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.glehenaff.gestform.view;

import java.util.List;
import org.glehenaff.gestform.GestForm;
import org.glehenaff.gestform.dao.AlreadyExistsException;
import org.glehenaff.gestform.dao.FormationDAO;
import org.glehenaff.gestform.model.Formation;
import org.glehenaff.gestform.model.Stagiaire;

/**
 *
 * @author gwenole
 */
public class AddStagToForm extends javax.swing.JDialog {

    private final StagTableModel tblStagModel;
    private final Formation formation;
    private final StagTableModel formStagTableModel;
    private final Form parent;

    /**
     * Creates new form AddStagToForm
     */
    public AddStagToForm(java.awt.Frame parent, boolean modal, Formation formation, StagTableModel formStagTableModel) {
        super(parent, modal);
        this.parent = (Form)parent;
        this.formation = formation;
        this.formStagTableModel = formStagTableModel;
        List<Stagiaire> stagiaires = GestForm.getDispoStagiaires();
        tblStagModel = new StagTableModel(stagiaires);
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBtn = new javax.swing.JPanel();
        addStag = new javax.swing.JButton();
        fermer = new javax.swing.JButton();
        panStag = new javax.swing.JPanel();
        sclStag = new javax.swing.JScrollPane();
        tblStag = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajouter un stagiaire à la formation");

        addStag.setBackground(new java.awt.Color(223, 240, 216));
        addStag.setForeground(new java.awt.Color(69, 118, 61));
        addStag.setText("Ajouter à la Formation");
        addStag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStagActionPerformed(evt);
            }
        });
        panBtn.add(addStag);

        fermer.setBackground(new java.awt.Color(217, 237, 247));
        fermer.setForeground(new java.awt.Color(49, 112, 143));
        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });
        panBtn.add(fermer);

        getContentPane().add(panBtn, java.awt.BorderLayout.PAGE_END);

        panStag.setLayout(new javax.swing.BoxLayout(panStag, javax.swing.BoxLayout.LINE_AXIS));

        tblStag.setModel(tblStagModel);
        sclStag.setViewportView(tblStag);

        panStag.add(sclStag);

        getContentPane().add(panStag, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStagActionPerformed
        try {
            for (int i : tblStag.getSelectedRows()) {
                Stagiaire s = tblStagModel.getStagiaire(i);
                FormationDAO.Instance().insert(formation, s);
                tblStagModel.remove(s);
                formStagTableModel.add(s);
            }
        } catch (AlreadyExistsException e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_addStagActionPerformed

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
        parent.RefreshData();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_fermerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStag;
    private javax.swing.JButton fermer;
    private javax.swing.JPanel panBtn;
    private javax.swing.JPanel panStag;
    private javax.swing.JScrollPane sclStag;
    private javax.swing.JTable tblStag;
    // End of variables declaration//GEN-END:variables
}
