/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.glehenaff.gestform.view;

/**
 *
 * @author gwenole
 */
public class Apropos extends javax.swing.JDialog {

    /**
     * Creates new form Apropos
     */
    public Apropos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogiciel = new javax.swing.JLabel();
        lblCopyright = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        lblLogiciel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogiciel.setText("Gestionnaire de formations v0.1");
        lblLogiciel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblLogiciel);

        lblCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyright.setText("Copyright G. LE HENAFF 2017");
        lblCopyright.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblCopyright);

        getContentPane().add(jPanel1);

        btnFermer.setText("Fermer");
        btnFermer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });
        jPanel2.add(btnFermer);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
        dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFermer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblLogiciel;
    // End of variables declaration//GEN-END:variables
}
