/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.glehenaff.gestform.view;

import java.util.List;
import javax.swing.DefaultListModel;
import org.glehenaff.gestform.model.Formation;
import org.glehenaff.gestform.model.Stagiaire;

/**
 *
 * @author gwenole
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    public void Refresh(List<Formation> formations, List<Stagiaire> stagiaires) {
        DefaultListModel listModel = new DefaultListModel();
        for (Formation formation : formations) {
            listModel.addElement(formation);
        }
        lstFormations.setModel(listModel);
        listModel = new DefaultListModel();
        for (Stagiaire stagiaire : stagiaires) {
            listModel.addElement(stagiaire);
        }
        lstStagiaires.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tbHaut = new javax.swing.JToolBar();
        btnActualiser = new javax.swing.JButton();
        panGauche = new javax.swing.JPanel();
        lblFormations = new javax.swing.JLabel();
        scrlForm = new javax.swing.JScrollPane();
        lstFormations = new javax.swing.JList<>();
        btnFormation = new javax.swing.JButton();
        btnEditForm = new javax.swing.JButton();
        btnSupprForm = new javax.swing.JButton();
        lblStagiaires = new javax.swing.JLabel();
        scrlStag = new javax.swing.JScrollPane();
        lstStagiaires = new javax.swing.JList<>();
        btnStagiaire = new javax.swing.JButton();
        btnFermer = new javax.swing.JButton();
        btnEditStag = new javax.swing.JButton();
        btnSupprStag = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionnaire de formation");

        tbHaut.setRollover(true);

        btnActualiser.setText("Actualiser");
        btnActualiser.setFocusable(false);
        btnActualiser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualiser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbHaut.add(btnActualiser);

        lblFormations.setText("Liste de formations");

        lstFormations.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrlForm.setViewportView(lstFormations);

        btnFormation.setBackground(new java.awt.Color(223, 240, 216));
        btnFormation.setForeground(new java.awt.Color(69, 118, 61));
        btnFormation.setText("Ajouter une Formation");
        btnFormation.setActionCommand("AddFormation");
        btnFormation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormationActionPerformed(evt);
            }
        });

        btnEditForm.setBackground(new java.awt.Color(252, 248, 227));
        btnEditForm.setForeground(new java.awt.Color(138, 109, 59));
        btnEditForm.setText("Modifier");
        btnEditForm.setEnabled(false);

        btnSupprForm.setBackground(new java.awt.Color(242, 222, 222));
        btnSupprForm.setForeground(new java.awt.Color(169, 68, 68));
        btnSupprForm.setText("Suppr.");
        btnSupprForm.setEnabled(false);
        btnSupprForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panGaucheLayout = new javax.swing.GroupLayout(panGauche);
        panGauche.setLayout(panGaucheLayout);
        panGaucheLayout.setHorizontalGroup(
            panGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGaucheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlForm)
                    .addComponent(lblFormations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panGaucheLayout.createSequentialGroup()
                        .addComponent(btnEditForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSupprForm))))
        );
        panGaucheLayout.setVerticalGroup(
            panGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGaucheLayout.createSequentialGroup()
                .addComponent(lblFormations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlForm, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditForm)
                    .addComponent(btnSupprForm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFormation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblStagiaires.setText("Liste des stagiaires");

        lstStagiaires.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrlStag.setViewportView(lstStagiaires);

        btnStagiaire.setBackground(new java.awt.Color(223, 240, 216));
        btnStagiaire.setForeground(new java.awt.Color(69, 118, 61));
        btnStagiaire.setText("Ajouter un Stagiaire");
        btnStagiaire.setActionCommand("AddStagiaire");
        btnStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStagiaireActionPerformed(evt);
            }
        });

        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        btnEditStag.setBackground(new java.awt.Color(252, 248, 227));
        btnEditStag.setForeground(new java.awt.Color(138, 109, 59));
        btnEditStag.setText("Modifier");
        btnEditStag.setEnabled(false);

        btnSupprStag.setBackground(new java.awt.Color(242, 222, 222));
        btnSupprStag.setForeground(new java.awt.Color(169, 68, 68));
        btnSupprStag.setText("Suppr.");
        btnSupprStag.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panGauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEditStag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSupprStag))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStagiaire, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblStagiaires, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addComponent(scrlStag))
                                    .addComponent(btnFermer)))))
                    .addComponent(tbHaut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbHaut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panGauche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStagiaires)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrlStag, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditStag)
                            .addComponent(btnSupprStag))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStagiaire)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnFermer)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormationActionPerformed
        AddFormation addFormation = new AddFormation();
        addFormation.setVisible(true);
    }//GEN-LAST:event_btnFormationActionPerformed

    private void btnStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStagiaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStagiaireActionPerformed

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    private void btnSupprFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupprFormActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualiser;
    private javax.swing.JButton btnEditForm;
    private javax.swing.JButton btnEditStag;
    private javax.swing.JButton btnFermer;
    private javax.swing.JButton btnFormation;
    private javax.swing.JButton btnStagiaire;
    private javax.swing.JButton btnSupprForm;
    private javax.swing.JButton btnSupprStag;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblFormations;
    private javax.swing.JLabel lblStagiaires;
    private javax.swing.JList<String> lstFormations;
    private javax.swing.JList<String> lstStagiaires;
    private javax.swing.JPanel panGauche;
    private javax.swing.JScrollPane scrlForm;
    private javax.swing.JScrollPane scrlStag;
    private javax.swing.JToolBar tbHaut;
    // End of variables declaration//GEN-END:variables
}
